version: '3.8'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "-b /opt/irisapp/vcopy.sh"
    init: true
    restart: always
    ports: 
      - 32769:51773
      - 32768:52773
      - 53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - zen/voldata

volumes:
  zen:
